/*
 * fetch-images.mjs — scrape each property's real WhataHotel hero image.
 *
 * Reads the property list from assets/js/data.js, fetches each property page,
 * extracts its og:image (the curated hero, ignoring the WhataHotel logo), and
 * writes assets/js/images.js:  window.WAH_IMAGES = { <id>: { hero: "<url>" } }.
 *
 * Run:  node scripts/fetch-images.mjs
 * (uses curl so it goes through the environment's HTTPS proxy)
 */
import { readFileSync, writeFileSync } from "node:fs";
import { execFile } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const OUT = join(root, "assets", "js", "images.js");

// Pull id + url pairs straight from the generated data file.
const dataSrc = readFileSync(join(root, "assets", "js", "data.js"), "utf8");
const pairs = [];
const re = /"id":\s*(\d+),\s*"url":\s*"([^"]+)"/g;
let m;
while ((m = re.exec(dataSrc)) !== null) pairs.push({ id: Number(m[1]), url: m[2] });
console.log("Properties to fetch:", pairs.length);

function curl(url) {
  return new Promise((resolve) => {
    execFile("curl", ["-sS", "-L", "--max-time", "40", url], { maxBuffer: 12 * 1024 * 1024 }, (err, stdout) => {
      resolve(err ? "" : stdout);
    });
  });
}

function heroFrom(html) {
  const metas = [...html.matchAll(/<meta[^>]+property="og:image"[^>]+content="([^"]+)"/gi)].map((x) => x[1]);
  // first og:image that isn't the site logo
  const hero = metas.find((u) => u && !/wah_logo/i.test(u));
  return hero || null;
}

// Small concurrency pool.
async function run(items, worker, concurrency) {
  const results = new Array(items.length);
  let i = 0;
  async function next() {
    const idx = i++;
    if (idx >= items.length) return;
    results[idx] = await worker(items[idx], idx);
    return next();
  }
  await Promise.all(Array.from({ length: Math.min(concurrency, items.length) }, next));
  return results;
}

const images = {};
let ok = 0, miss = 0;
await run(pairs, async (p) => {
  const html = await curl(p.url);
  const hero = html ? heroFrom(html) : null;
  if (hero) { images[p.id] = { hero }; ok++; }
  else { miss++; console.warn("  no image:", p.id, p.url); }
}, 8);

console.log(`Fetched heroes: ${ok} ok, ${miss} missing`);

const header = `/*
 * WhataHotel! — real property hero images
 * AUTO-GENERATED by scripts/fetch-images.mjs (each property's og:image hero).
 * Re-run:  node scripts/fetch-images.mjs
 * Consumed by homes.js imageFor(); the CSS/SVG scene is the fallback.
 */
window.WAH_IMAGES = `;
// stable ordering by id
const ordered = {};
Object.keys(images).map(Number).sort((a, b) => a - b).forEach((id) => { ordered[id] = images[id]; });
writeFileSync(OUT, header + JSON.stringify(ordered, null, 2) + ";\n");
console.log("Wrote", OUT);
